export const SAVE_USER_MESSAGE_TO_API = 'USER_MESSAGE/SAVE_USER_MESSAGE_TO_API';
export const SAVE_USER_MESSAGE_TO_STORE = 'USER_MESSAGE/SAVE_USER_MESSAGE_TO_STORE';
export const LOAD_DATA_FROM_API = 'LOAD_DATA_FROM_API/LOAD_DATA_FROM_API';
export const SAVE_MESSAGES_FROM_API = 'LOAD_DATA_FROM_API/SAVE_MESSAGES_FROM_API';
